// French text constants - Single language mode
export const FR = {
  nav: {
    home: "Accueil",
    recipes: "Recettes",
    products: "Produits",
    deals: "Promotions",
    bundles: "Lots",
    categories: "Catégories",
    supermarkets: "Supermarchés",
    videos: "Vidéos",
    about: "À propos",
    contact: "Contact",
    search: "Rechercher des produits...",
    searchVideos: "Rechercher des vidéos...",
    cart: "Panier",
    wishlist: "Liste de souhaits",
    login: "Connexion",
    logout: "Déconnexion",
    admin: "Admin",
    account: "Mon Compte",
    myOrders: "Mes Commandes",
    myVideos: "Mes Vidéos",
    language: "Langue"
  },
  common: {
    new: "NOUVEAU",
    bestSeller: "Meilleure Vente",
    freeShipping: "Livraison Gratuite",
    addToCart: "Ajouter au panier",
    viewProduct: "Voir le produit",
    browseCategory: "Parcourir la catégorie",
    items: "articles",
    products: "produits",
    loading: "Chargement...",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    create: "Créer",
    back: "Retour",
    next: "Suivant",
    prev: "Précédent",
    previous: "Précédent",
    search: "Rechercher",
    filter: "Filtrer",
    sortBy: "Trier par",
    newest: "Le plus récent",
    priceLowHigh: "Prix: du moins cher au plus cher",
    priceHighLow: "Prix: du plus cher au moins cher",
    showing: "Affichage",
    results: "résultats",
    of: "de",
    page: "Page",
    noResults: "Aucun résultat trouvé.",
    yes: "Oui",
    no: "Non",
    submit: "Soumettre",
    submitting: "Envoi en cours...",
    outOfStock: "Rupture de stock",
    inStock: "En stock",
    onlyXLeft: "Il ne reste que {count} en stock",
    you_save: "Vous économisez"
  },
  home: {
    heroBadge: "Plateforme Culinaria — Depuis 2024",
    heroTitle: "Découvrez des Recettes et des Ingrédients Locaux",
    heroSubtitle: "Trouvez des recettes inspirantes et les ingrédients dont vous avez besoin dans les supermarchés locaux, le tout au même endroit.",
    heroCtaRecipes: "Explorer les Recettes",
    heroCtaSupermarkets: "Découvrir les Supermarchés",
    heroCtaShop: "Explorer les Recettes",
    heroCtaContact: "Découvrir les Supermarchés",
    newRecipes: "Nouvelles Recettes",
    newRecipesSubtitle: "Les dernières créations de notre communauté de cuisiniers.",
    newArrivals: "Nouvelles Recettes",
    newArrivalsSubtitle: "Les dernières créations de notre communauté de cuisiniers.",
    hotDeals: "Recettes Populaires",
    hotDealsSubtitle: "Les recettes les plus aimées et partagées cette semaine.",
    trending: "Recettes Populaires",
    trendingSubtitle: "Les recettes les plus aimées et partagées cette semaine.",
    categories: "Catégories de Recettes",
    categoriesSubtitle: "Parcourez par type de cuisine, régime alimentaire ou occasion",
    shopByCategory: "Catégories de Recettes",
    shopByCategorySubtitle: "Parcourez par type de cuisine, régime alimentaire ou occasion",
    featured: "Supermarchés Partenaires",
    featuredSubtitle: "Trouvez les meilleurs supermarchés locaux pour vos ingrédients",
    testimonials: "Ce que disent nos utilisateurs",
    testimonialsSubtitle: "Des milliers de cuisiniers amateur utilisent My Recette pour simplifier leur cuisine.",
    howItWorks: "Comment ça marche",
    step1: "Trouvez des recettes",
    step2: "Vérifiez les ingrédients",
    step3: "Faites vos courses",
    directions: "Commencer",
    visitUs: "Rejoignez Notre Communauté",
    visitUsSubtitle: "Connectez-vous avec des milliers de cuisiniers amateurs partageant des recettes et des conseils.",
    address: "Plateforme en ligne",
    hours: "Disponible 24/7",
    phone: "Support client",
    viewAll: "Voir toutes les recettes"
  },
  products: {
    title: "Tous les Produits",
    subtitle: "Ingrédients de haute qualité et approvisionnement de cuisine pour toutes vos besoins culinaires.",
    filters: "Filtres",
    allCategories: "Toutes les catégories",
    priceRange: "Fourchette de prix",
    availability: "Disponibilité",
    newArrivalsOnly: "Nouvelles Arrivées Seulement",
    onSaleOnly: "En Promotion Seulement",
    freeShipping: "Livraison Gratuite",
    searchPlaceholder: "Rechercher des produits...",
    noProducts: "Aucun produit ne correspond à vos filtres."
  },
  // Add more namespaces as needed...
} as const;

export type FRType = typeof FR;